TRANSPORT_DATA = {
    "flight": [
        {"id": "FL001", "name": "IndiGo 6E-201", "source": "delhi", "destination": "mumbai", "departure": "06:00", "arrival": "08:10", "duration": "2h 10m", "cost": 4500, "seats": 180, "airline": "IndiGo"},
        {"id": "FL002", "name": "Air India AI-301", "source": "delhi", "destination": "mumbai", "departure": "09:30", "arrival": "11:45", "duration": "2h 15m", "cost": 5200, "seats": 220, "airline": "Air India"},
        {"id": "FL003", "name": "SpiceJet SG-101", "source": "delhi", "destination": "mumbai", "departure": "14:00", "arrival": "16:15", "duration": "2h 15m", "cost": 3800, "seats": 160, "airline": "SpiceJet"},
        {"id": "FL004", "name": "Vistara UK-501", "source": "delhi", "destination": "mumbai", "departure": "18:30", "arrival": "20:40", "duration": "2h 10m", "cost": 6100, "seats": 200, "airline": "Vistara"},
        {"id": "FL005", "name": "IndiGo 6E-401", "source": "mumbai", "destination": "bangalore", "departure": "07:15", "arrival": "08:30", "duration": "1h 15m", "cost": 3200, "seats": 180, "airline": "IndiGo"},
        {"id": "FL006", "name": "Air India AI-601", "source": "mumbai", "destination": "bangalore", "departure": "11:00", "arrival": "12:20", "duration": "1h 20m", "cost": 4100, "seats": 220, "airline": "Air India"},
        {"id": "FL007", "name": "SpiceJet SG-701", "source": "bangalore", "destination": "hyderabad", "departure": "08:00", "arrival": "09:00", "duration": "1h 00m", "cost": 2900, "seats": 160, "airline": "SpiceJet"},
        {"id": "FL008", "name": "Vistara UK-801", "source": "hyderabad", "destination": "chennai", "departure": "13:30", "arrival": "14:40", "duration": "1h 10m", "cost": 3500, "seats": 200, "airline": "Vistara"},
        {"id": "FL009", "name": "IndiGo 6E-901", "source": "chennai", "destination": "kolkata", "departure": "16:00", "arrival": "18:30", "duration": "2h 30m", "cost": 4800, "seats": 180, "airline": "IndiGo"},
        {"id": "FL010", "name": "Air India AI-201", "source": "kolkata", "destination": "delhi", "departure": "20:00", "arrival": "22:30", "duration": "2h 30m", "cost": 5500, "seats": 220, "airline": "Air India"},
        {"id": "FL011", "name": "GoFirst G8-101", "source": "delhi", "destination": "goa", "departure": "07:00", "arrival": "09:30", "duration": "2h 30m", "cost": 5800, "seats": 180, "airline": "GoFirst"},
        {"id": "FL012", "name": "IndiGo 6E-601", "source": "mumbai", "destination": "goa", "departure": "10:00", "arrival": "11:10", "duration": "1h 10m", "cost": 2500, "seats": 180, "airline": "IndiGo"},
    ],
    "train": [
        {"id": "TR001", "name": "Rajdhani Express", "source": "delhi", "destination": "mumbai", "departure": "16:25", "arrival": "08:35+1", "duration": "16h 10m", "cost": 1850, "seats": 500, "train_no": "12951"},
        {"id": "TR002", "name": "Shatabdi Express", "source": "delhi", "destination": "mumbai", "departure": "06:00", "arrival": "22:10", "duration": "16h 10m", "cost": 1450, "seats": 450, "train_no": "12009"},
        {"id": "TR003", "name": "Duronto Express", "source": "mumbai", "destination": "bangalore", "departure": "23:00", "arrival": "13:30+1", "duration": "14h 30m", "cost": 1650, "seats": 480, "train_no": "12201"},
        {"id": "TR004", "name": "Garib Rath", "source": "delhi", "destination": "kolkata", "departure": "22:30", "arrival": "18:00+1", "duration": "19h 30m", "cost": 950, "seats": 600, "train_no": "12203"},
        {"id": "TR005", "name": "Chennai Express", "source": "mumbai", "destination": "chennai", "departure": "06:00", "arrival": "06:45+1", "duration": "24h 45m", "cost": 1350, "seats": 500, "train_no": "11041"},
        {"id": "TR006", "name": "Deccan Queen", "source": "mumbai", "destination": "pune", "departure": "07:15", "arrival": "10:25", "duration": "3h 10m", "cost": 450, "seats": 350, "train_no": "12123"},
        {"id": "TR007", "name": "Vande Bharat", "source": "hyderabad", "destination": "bangalore", "departure": "06:00", "arrival": "10:30", "duration": "4h 30m", "cost": 1250, "seats": 400, "train_no": "20701"},
        {"id": "TR008", "name": "Golconda Express", "source": "hyderabad", "destination": "chennai", "departure": "18:15", "arrival": "06:00+1", "duration": "11h 45m", "cost": 1100, "seats": 480, "train_no": "12759"},
        {"id": "TR009", "name": "Howrah Mail", "source": "kolkata", "destination": "delhi", "departure": "19:55", "arrival": "17:30+1", "duration": "21h 35m", "cost": 1200, "seats": 520, "train_no": "12311"},
        {"id": "TR010", "name": "Sampark Kranti", "source": "bangalore", "destination": "delhi", "departure": "20:30", "arrival": "07:15+2", "duration": "34h 45m", "cost": 2100, "seats": 450, "train_no": "12627"},
    ],
    "bus": [
        {"id": "BU001", "name": "KSRTC Volvo AC", "source": "bangalore", "destination": "hyderabad", "departure": "21:00", "arrival": "07:00+1", "duration": "10h 00m", "cost": 850, "seats": 40, "operator": "KSRTC"},
        {"id": "BU002", "name": "RedBus Sleeper", "source": "bangalore", "destination": "hyderabad", "departure": "22:30", "arrival": "08:30+1", "duration": "10h 00m", "cost": 950, "seats": 36, "operator": "RedBus"},
        {"id": "BU003", "name": "TSRTC Express", "source": "hyderabad", "destination": "bangalore", "departure": "20:00", "arrival": "06:00+1", "duration": "10h 00m", "cost": 750, "seats": 45, "operator": "TSRTC"},
        {"id": "BU004", "name": "SRS Travels AC", "source": "mumbai", "destination": "pune", "departure": "07:00", "arrival": "10:30", "duration": "3h 30m", "cost": 350, "seats": 40, "operator": "SRS Travels"},
        {"id": "BU005", "name": "Neeta Volvo", "source": "mumbai", "destination": "goa", "departure": "22:00", "arrival": "08:00+1", "duration": "10h 00m", "cost": 900, "seats": 36, "operator": "Neeta Tours"},
        {"id": "BU006", "name": "APSRTC Garuda", "source": "hyderabad", "destination": "chennai", "departure": "20:30", "arrival": "07:00+1", "duration": "10h 30m", "cost": 800, "seats": 42, "operator": "APSRTC"},
        {"id": "BU007", "name": "IntrCity Sleeper", "source": "delhi", "destination": "jaipur", "departure": "22:00", "arrival": "04:30+1", "duration": "6h 30m", "cost": 550, "seats": 36, "operator": "IntrCity"},
        {"id": "BU008", "name": "Raj National", "source": "jaipur", "destination": "delhi", "departure": "21:00", "arrival": "03:30+1", "duration": "6h 30m", "cost": 500, "seats": 40, "operator": "Raj National"},
        {"id": "BU009", "name": "Orange Tours", "source": "chennai", "destination": "bangalore", "departure": "23:00", "arrival": "05:30+1", "duration": "6h 30m", "cost": 650, "seats": 40, "operator": "Orange Tours"},
        {"id": "BU010", "name": "Parveen Travels", "source": "bangalore", "destination": "chennai", "departure": "22:00", "arrival": "05:00+1", "duration": "7h 00m", "cost": 700, "seats": 40, "operator": "Parveen Travels"},
    ]
}

HOTEL_DATA = [
    {"id": "HT001", "name": "The Taj Mahal Palace", "location": "mumbai", "rating": 5, "cost": 18000, "amenities": ["Pool", "Spa", "WiFi", "Restaurant", "Gym"], "image": "taj.jpg", "description": "Iconic luxury hotel overlooking the Arabian Sea with timeless elegance."},
    {"id": "HT002", "name": "ITC Grand Chola", "location": "chennai", "rating": 5, "cost": 15000, "amenities": ["Pool", "Spa", "WiFi", "Restaurant", "Gym", "Casino"], "image": "itc.jpg", "description": "A palatial hotel inspired by the grandeur of the Chola dynasty."},
    {"id": "HT003", "name": "The Leela Palace", "location": "delhi", "rating": 5, "cost": 20000, "amenities": ["Pool", "Spa", "WiFi", "Restaurant", "Butler"], "image": "leela.jpg", "description": "Ultra-luxury hotel in the heart of New Delhi with world-class amenities."},
    {"id": "HT004", "name": "Oberoi Bengaluru", "location": "bangalore", "rating": 5, "cost": 14000, "amenities": ["Pool", "Spa", "WiFi", "Restaurant", "Gym"], "image": "oberoi.jpg", "description": "Serene luxury retreat amidst lush greenery in the garden city."},
    {"id": "HT005", "name": "Novotel Hyderabad", "location": "hyderabad", "rating": 4, "cost": 8500, "amenities": ["Pool", "WiFi", "Restaurant", "Gym"], "image": "novotel.jpg", "description": "Contemporary comfort hotel near the convention center."},
    {"id": "HT006", "name": "Vivanta Goa", "location": "goa", "rating": 5, "cost": 12000, "amenities": ["Beachfront", "Pool", "Spa", "WiFi", "Restaurant"], "image": "vivanta.jpg", "description": "Beachfront paradise with stunning sunset views and tropical vibes."},
    {"id": "HT007", "name": "Marriott Jaipur", "location": "jaipur", "rating": 5, "cost": 11000, "amenities": ["Pool", "Spa", "WiFi", "Restaurant", "Heritage Tours"], "image": "marriott.jpg", "description": "Royal heritage hotel capturing the essence of the Pink City."},
    {"id": "HT008", "name": "Courtyard by Marriott", "location": "kolkata", "rating": 4, "cost": 7500, "amenities": ["Pool", "WiFi", "Restaurant", "Business Center"], "image": "courtyard.jpg", "description": "Modern business hotel in the cultural capital of India."},
    {"id": "HT009", "name": "Hyatt Regency Mumbai", "location": "mumbai", "rating": 5, "cost": 16000, "amenities": ["Pool", "Spa", "WiFi", "Restaurant", "Gym", "Club Lounge"], "image": "hyatt.jpg", "description": "Sleek skyscraper hotel offering panoramic city views."},
    {"id": "HT010", "name": "Fortune Park", "location": "bangalore", "rating": 4, "cost": 6000, "amenities": ["WiFi", "Restaurant", "Gym", "Conference Room"], "image": "fortune.jpg", "description": "Comfortable mid-range hotel perfect for business and leisure."},
    {"id": "HT011", "name": "Lemon Tree Hotel", "location": "hyderabad", "rating": 3, "cost": 4500, "amenities": ["WiFi", "Restaurant", "Gym"], "image": "lemon.jpg", "description": "Cheerful budget-friendly hotel with great connectivity."},
    {"id": "HT012", "name": "Sterling Goa", "location": "goa", "rating": 4, "cost": 8000, "amenities": ["Pool", "Beach Access", "WiFi", "Restaurant"], "image": "sterling.jpg", "description": "Comfortable resort steps away from the golden sands of Goa."},
]
